### ISSUE TITLE
v2 cannot resolve a page with parameters using UsePageResolver

### ISSUE THREAD

**Issue by AntPolkanov** [matt-goldman/Maui.Plugins.PageResolver#26]
**Describe the bug**
I want to explicitly register dependencies using `UsePageResolver`, and one of my pages accepts a view model and a parameter.
After upgrading to v2 (v1.1.1 works fine), I get the following error:

System.InvalidOperationException: A suitable constructor for type 'DemoProject.PageParamPage' could not be located. Ensure the type is concrete and all parameters of a public constructor are either registered as services or passed as arguments. Also ensure no extraneous arguments are provided.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.FindApplicableConstructor(Type instanceType, Type[] argumentTypes, ConstructorInfo& matchingConstructor, Nullable`1[]& matchingParameterMap)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance[PageParamPage](IServiceProvider provider, Object[] parameters)
   at Maui.Plugins.PageResolver.NavigationExtensions.**CreatePageWithoutViewModel**[PageParamPage](IServiceProvider serviceProvider, Object[] parameters) in /Users/antonpolkanov/projects/Maui.Plugins.PageResolver/src/Maui.Plugins.PageResolver/NavigationExtensions.cs:line 89
   at Maui.Plugins.PageResolver.NavigationExtensions.ResolvePage[PageParamPage](Object[] parameters) in /Users/antonpolkanov/projects/Maui.Plugins.PageResolver/src/Maui.Plugins.PageResolver/NavigationExtensions.cs:line 81
   at Maui.Plugins.PageResolver.NavigationExtensions.<PushAsync>d__21[[DemoProject.PageParamPage, DemoProject, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext() in /Users/antonpolkanov/projects/Maui.Plugins.PageResolver/src/Maui.Plugins.PageResolver/NavigationExtensions.cs:line 54
   at DemoProject.ViewModels.MainViewModel.GoToPageParamPage() in /Users/antonpolkanov/projects/Maui.Plugins.PageResolver/src/DemoProject/ViewModels/MainViewModel.cs:line 38
   at DemoProject.ViewModels.MainViewModel.<get_GoToPageParamCommand>b__4_0() in /Users/antonpolkanov/projects/Maui.Plugins.PageResolver/src/DemoProject/ViewModels/MainViewModel.cs:line 12
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:line 36
   at Java.Lang.Thread.RunnableImplementor.Run() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:line 36
   at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Java.Lang.IRunnable.cs:line 84
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 26_

**To Reproduce**
1. Go to the DemoProject
2. Replace `UseAutodependencies` with `UsePageResolver`
3. Register 2 pages and a service for the app to run
```
            builder.Services.AddSingleton<INameService, NameService>();
            builder.Services.AddSingleton(typeof(MainPage));
            builder.Services.AddSingleton(typeof(MainViewModel));
            builder.Services.AddSingleton(typeof(PageParamPage));
            builder.Services.AddSingleton(typeof(PageParamViewModel));
```
4. Run the app
5. Tap "Click to go to page param page" button

**Expected behavior**
The page opens and passed parameter ("Maui") is displayed on the page

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by matt-goldman** [comment]
Have you tried this? https://github.com/matt-goldman/Maui.Plugins.PageResolver/wiki/1-Using-the-PageResolver#option-3-pass-the-dictionary-manually

**Comment by matt-goldman** [comment]
Hey @AntPolkanov can this be closed?

**Comment by AntPolkanov** [comment]
@matt-goldman, yes it can be closed. Thanks for the link.
