### ISSUE TITLE
.NET 9 

### ISSUE THREAD

**Issue by IeuanWalker** [matt-goldman/Maui.Plugins.PageResolver#42]
**Describe the bug**
Updated app to .net 9 getting the following error -

```
{System.InvalidOperationException: PushAsync is not supported, please use a NavigationPage.
   at Microsoft.Maui.Controls.Window.NavigationImpl.OnPushAsync(Page page, Boolean animated) in /_/src/Controls/src/Core/Window/Window.cs:line 706
   at Microsoft.Maui.Controls.Internals.NavigationProxy.PushAsync(Page root, Boolean animated) in /_/src/Controls/src/Core/NavigationProxy.cs:line 135
   at Microsoft.Maui.Controls.Internals.NavigationProxy.PushAsync(Page root) in /_/src/Controls/src/Core/NavigationProxy.cs:line 127
   at App.Features.Navigation.NavigationFeature.PushAsync(Page page) in D:\WS\Azure-CardiffCouncilICT\App\src\App\Features\Navigation\NavigationFeature.cs:line 70
   at Maui.Plugins.PageResolver.NavigationExtensions.<PushAsync>d__2`1[[App.Routes.WasteManagement.WasteCalendar.Pages.DisplayPage, App, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at App.Routes.WasteManagement.WasteCalendar.ViewModels.AddressSearchViewModel.Search() in D:\WS\Azure-CardiffCouncilICT\App\src\App\Routes\WasteManagement\WasteCalendar\ViewModels\AddressSearchViewModel.cs:line 89}
```
 
![image](https://github.com/user-attachments/assets/847db700-880d-4ffd-b33c-0dd0a5ad6a8b)

**To Reproduce**
Will try to debug and see if i can see whats going on, just raising this incase anyone else has an idea

**Comment by IeuanWalker** [comment]
Seams to be only an issue for pages that take in a parameter aswell

**Comment by matt-goldman** [comment]
Weird, the demo project is .NET 9 and works ok. Definitely no other changes in your app? That error usually occurs when you don't have a navigation stack, which obviously wouldn't be the case here. 

Looking at your additional comment, it's probably to do with a change in the behavior of `ActivatorUtilities` in .NET 9. I'll see if I can replicate it.

**Comment by IeuanWalker** [comment]
@matt-goldman sorry forgot to update this, made a mistake when updating stuff to .net 9 - 
![image](https://github.com/user-attachments/assets/3e2b0d19-21fc-456f-bf9a-d2d65a878461)
